### ISSUE TITLE
Some Questions (???)

### ISSUE THREAD

**Issue by AGhasemzadeh** [rennokki/guardian#15]
Hello,
I found your package is very useful.
Just I have some questions about it.
1-Do you use any cache for permissions?
2-How we can manage user groups (I mean Roles)? 
3-Is there any blade directive like @can() or @cant() ?
4-For current user how we can use package?

**Comment by rennokki** [comment]
Hi @AGhasemzadeh ,

I'm glad it seems useful to you. I will answer to the questions, point-by-point:

1. No, there is no such cached permissions. This seems like a good feature, and i'll hit the Project Board with this. It will be implemented soon.
2. There are no roles. The fact that Guardian is simple is that what it does more is manage permissions, one-by-one. The main advantage that thish package has, and why it was build, was for `Global Type` and `Global Specific Type` permissions, that can help any user control certain models, as i have stated in the examples with Post and ChatRoom models.
3. The Project Board currently has a card with Blade Directives, and as soon as i get to read docs about Blade Directives, that'll be implemented too.
4. For the current user (the model that implements Authenticatable) i highly recommend working with `Middleware` and filter those two exceptions in your `Handler.php` or anywhere else. You can also add the `HasPermissions` trait to your user model and use the `$request->user()` or `request()->user()` methods from which you can call the methods within this package.

If you have any other questions or improvements, feel free to address them. :D
